apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleaseStrategy
metadata:
  name: push-to-external-registry-strategy
  namespace: bcook-managed-tenant
spec:
  params:
    - name: extraConfigGitUrl
      value: https://github.com/brianwcook/demo-strategy-config.git
    - name: extraConfigPath
      value: strategy-config.yaml
    - name: extraConfigRevision
      value: main
    - name: pyxisServerType
      value: stage
    - name: pyxisSecret
      value: pyxis
    - name: tag
      value: latest
    - name: addGitShaTag
      value: "true"
  pipeline: push-to-external-registry
  bundle: quay.io/hacbs-release/pipeline-push-to-external-registry:main
  policy: demo-policy
  serviceAccount: release-service-account
